import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-screen w-full m-0'>
      <body className={`${inter.className} bg-gradient-radial m-0 h-screen w-full`}>{children}</body>
    </html>
  )
}
