import Navbar from './components/Navbar'
import Providers from './components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full w-full m-0 p-0'>
      <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
      <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      <body className={`${inter.className} bg-gradient-radial m-0 h-full w-full flex flex-col`}>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
        </body>
    </html>
  )
}
