export enum ErrorTypes {
    LENGTH = "LENGTH", 
    NOT_EQUAL = "NOT_EQUAL",
    BLANK_EMAIL = "BLANK_EMAIL",
    BLANK_PASSWORD = "BLANK_PASSWORD",
    BLANK_RE_PASSWORD = "BLANK_RE_PASSWORD",
    NONE = "NONE",
    EMAIL_EXISTS = "EMAIL_EXISTS",
    INVALID_EMAIL = "INVALID_EMAIL"
}